# This is the Makefile for the frontend of the project
# Commands in this file can be run by running `make <command name>` in the terminal.

.PHONY: setup_frontend
setup_frontend:
	npm install

.PHONY: start_frontend
start_frontend:
	npm run dev