version: '3'
services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Adjust the port mapping as needed
    # Add any other frontend service configuration here

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjust the port mapping as needed
    # Add any other backend service configuration here