[tool.poetry]
name = "wdxsay"
version = "0.1.0"
description = "what does x say about y"
authors = ["Anand Tyagi <anand.deep.tyagi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
